### PR TITLE
ci: macos-latest is changing to macos-14 ARM runners

### PR DESCRIPTION
**Pull request by henryiii**
Committed via https://github.com/asottile/all-repos

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
Hello @henryiii, @HDembinski, will you adding support for Python 3.12 here or better do it in a dedicated PR? Indeed I was working on the scikit-hep metapackage and believe only resample needs to support 3.12 to be able to have scikit-hep support 3.12 as well. Advance thanks.

**Comment by henryiii** [comment]
FYI, 3.8 and 3.9 was added to macOS ARM on GHA, so this PR might no longer be needed. So I’d suggest a separate PR.

**Comment by eduardo-rodrigues** [comment]
Fair enough. I just wanted to highlight the relatively need to support 3.12 at this point.

**Comment by henryiii** [comment]
Isn’t there a 3.12 test, though? The windows job?

**Comment by eduardo-rodrigues** [comment]
Oh, that's right! But there is no support in the sense that the metadata does not state it.

**Comment by henryiii** [comment]
Added #188. But that’s metadata is just informational.

**Comment by henryiii** [comment]
macOS latest on ARM is fine in #189.

**Pull request closed without merging**
